trigger:
- master

pool:
  vmImage: 'windows-latest' # 也可使用 'ubuntu-latest'，更快

steps:
# ======================================================
# Node.js 版本必須符合 Angular v16 的要求
# ======================================================
- task: NodeTool@0
  inputs:
    versionSpec: '18.x' # Angular v16 必須使用 16.x 或 18.x。
  displayName: 'Install Node.js 18.x' 


# (步驟 1: 安裝依賴)
- script: npm ci
  displayName: '1. Install Dependencies (npm ci)'

# (步驟 2: 建置專案)
- script: npx ng build --configuration=production --base-href /demo/
  displayName: '2. Build Angular App (npx ng build)'


# ======================================================
# CD 步驟: 部署到 GitHub Pages
# ======================================================


# 印出資訊 (debug用)
- script: |
    echo "--- Debug Information ---"
    echo "Build Number: $(Build.BuildNumber)"
    echo "Source Branch: $(Build.SourceBranchName)"
    echo "Working Directory: $(System.DefaultWorkingDirectory)"
    echo "--------------------------"
  displayName: 'Print System Variables'


- task: GitHubPagesPublish@1
  inputs:
    docPath: '$(System.DefaultWorkingDirectory)/dist/demo/*'
    
    githubusername: 'ShawnYen1123'
    githubemail: 'shawnyen@hotmail.com'
    githubaccesstoken: '$(token)' 
    repositoryname: 'demo'
    branchname: 'gh-pages'
    commitmessage: 'Automated Deploy from Build $(Build.BuildNumber)'