trigger:
- master

pool:
  vmImage: 'windows-latest' # 推薦使用 'ubuntu-latest'，它更快

steps:
# ======================================================
# Node.js 版本必須符合 Angular v16 的要求
# ======================================================
- task: NodeTool@0
  inputs:
    versionSpec: '18.x' # Angular v16 必須使用 16.x 或 18.x。
  displayName: 'Install Node.js 18.x' 


# (步驟 1: 安裝依賴)
- script: npm ci
  displayName: '1. Install Dependencies (npm ci)'

# (步驟 2: 建置專案)
#
# (!!!) 如果這一步失敗，請點開 Log 並貼上紅字錯誤 (!!!)
#
- script: npx ng build --configuration=production --base-href /demo/
  displayName: '2. Build Angular App (npx ng build)'


# ======================================================
# CD 步驟: 部署到 GitHub Pages
# ======================================================
- task: GitHubPagesPublish@1
  inputs:
    docPath: '$(System.DefaultWorkingDirectory)/demo' # 假設專案名稱為 'demo'
    
    githubusername: 'ShawnYen1123'
    githubemail: 'yrs791123@hotmail.com'
    githubaccesstoken: '$(token)' 
    repositoryname: 'demo'
    branchname: 'gh-pages'
    
    # 
    # (修正 4) 修正 Commit Message 的變數
    # 
    commitmessage: 'Automated Deploy from Build $(Build.BuildNumber)'